export const noteActionTyoes = {
    FETCH_NOTES: 'FETCH_NOTES',
    DELETE_NOTE: 'DELETE_NOTE',
    CREATE_NOTE: 'CREATE_NOTE',
    WRITE_NOTE: 'WRITE_NOTE',
    EDIT_NOTE: 'EDIT_NOTE',
    UPDATE_NOTE: 'UPDATE_NOTE',
    TOGGLE_FAVORITES: 'TOGGLE_FAVORITES',
    GET_FAVORITES: 'GET_FAVORITES'
}